version: 2

workflows:
  version: 2
  test:
    jobs:
      - test27
      - test35
      - test36
      - test37

_test-body:
  - &_dep
    run:
      name: install dependencies
      command: |
        . venv/bin/activate
        python setup.py install
        pip install -r devel-requirements.txt
  - &_test
    run:
      name: run tests
      command: |
        . venv/bin/activate
        python test_pyjq.py

jobs:
  test27:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: create venv
          command: python -m virtualenv venv
      - *_dep
      - *_test

  test35:
    docker:
      - image: circleci/python:3.5
    steps: &_py3_steps
      - checkout
      - run:
          name: create venv
          command: python -m venv venv
      - *_dep
      - *_test

  test36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: create venv
          command: python -m venv venv
      - *_dep
      - *_test

  test37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: create venv
          command: python -m venv venv
      - *_dep
      - *_test
